prompt={'Where is the data file? ', 'What is the delimiter (''\t'', ''.'' , '','' , etc.)? '};
name='uinput';
numlines=1;
defaultanswer={'~/mrperfcs386m/test/data.dat', '\t'};
answer=inputdlg(prompt,name,numlines,defaultanswer);
A = importdata(answer{1}, answer{2});

% sprintf('~/mrperfcs386m/test/data.dat'); 
% file = input('Where is the data file? ', 's');
% sprintf('\\t');
% delim = input('What is the delimiter (\\t, . , etc.)? ', 's');
% A = importdata(file, delim);

figure(1);
clf;

%set(axes,'XDir','default','YDir','reverse');
hold on;

data = line(A(:,2),A(:,1));
data2 = line(A(:,4),A(:,3));

set(data                          , ...
  'LineWidth'       , 2           );
set(data,'Color', [0 0 .5]);
set(data, ...
    'Marker', 'o', ...
    'MarkerSize', 4, ...
    'MarkerEdgeColor','none', ...
    'MarkerFaceColor', [.75 .75 1] );

set(data2                          , ...
  'LineWidth'       , 2            , ...
  'LineStyle'       , '-'          );
set(data2,'Color', [.5 0 .5]);
set(data2, ...
    'Marker', 'x', ...
    'MarkerSize', 4, ...
    'MarkerEdgeColor', [.75 .75 1], ...
    'MarkerFaceColor', [.75 .75 1] );

gtitle = title('Test');
xl = xlabel('Seconds');
yl = ylabel('Nodes');
leg = legend([data, data2], 'Grid', 'Data Center','location','NorthWest');

set( [gca, gtitle]         , ...
    'FontName'   , 'Helvetica' );
set([xl, yl], ...
    'FontName'   , 'AvantGarde');
set([leg, gca]             , ...
    'FontSize'   , 10           );
set([xl, yl]  , ...
    'FontSize'   , 10          );
set( gtitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
% 
% 
% set([gca], 'FontSize', 18);
% set([xl,yl,leg], 'FontSize', 16);
% set([xl,yl,leg], 'FontName', 'Garamond');

set(gca, ...
  'FontName'    , 'Garamond', ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

set(gcf, 'PaperPositionMode', 'auto');

plot(data);